import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme, ThemeContext } from "@radix-ui/themes";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
         <header>
          <Header/>
         </header>
          <main>
            <SideBar/>
             {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
