import { NextResponse } from 'next/server';

// Helper function to generate a random ID
const generateId = () => Math.random().toString(36).substr(2, 9);

// Data for all 20 MRN details
const mrnDetails = [
    {
        issueNo: 'ISS-1001',
        mrnId: '15-0000475',
        location: 'Main Pharmacy',
        store: 'Central Store',
        requesterDate: '2024-01-10',
        requestedBy: 'Dr. John Smith',
        approvedDate: '2024-01-12',
        approvedBy: 'Pharmacy Manager A',
        issuedDate: '2024-01-14',
        issuedBy: 'Pharmacist B',
        receivedDate: '2024-01-15',
        status: 'Approved',
        issuedStatus: 'Received',
        date: '2024-01-15',
        time: '10:00:00',
        requestedLocation: 'Main Pharmacy',
        issuedInStore: 'Central Store',
        mrnStatus: 'Received',
        items: [
        { id: generateId(), slNo: 1, itemCode: 'MED001', itemName: 'Paracetamol 500mg', uom: 'tab', reqQty: 100, apprQty: 100, issuedQty: 100, recQty: 100, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 2, itemCode: 'MED002', itemName: 'Dolo 650mg', uom: 'tab', reqQty: 80, apprQty: 80, issuedQty: 80, recQty: 80, rejQty: 0, balQty: 0, remarks: '', urgReq: true },
        { id: generateId(), slNo: 3, itemCode: 'MED003', itemName: 'Amoxicillin 500mg', uom: 'cap', reqQty: 60, apprQty: 60, issuedQty: 60, recQty: 60, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 4, itemCode: 'MED004', itemName: 'Cough Syrup 100ml', uom: 'ml', reqQty: 20, apprQty: 20, issuedQty: 20, recQty: 20, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 5, itemCode: 'MED005', itemName: 'Vitamin C 500mg', uom: 'tab', reqQty: 50, apprQty: 50, issuedQty: 50, recQty: 50, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        ],
    },
    {
        issueNo: 'ISS-1002',
        mrnId: '15-0000476',
        location: 'Emergency Ward',
        store: 'Pharmacy Store',
        requesterDate: '2024-01-11',
        requestedBy: 'Dr. Alice Brown',
        approvedDate: '2024-01-13',
        approvedBy: 'Pharmacy Manager B',
        issuedDate: '2024-01-15',
        issuedBy: 'Pharmacist C',
        receivedDate: '2024-01-16',
        status: 'Pending',
        issuedStatus: 'Not Issued',
        date: '2024-01-16',
        time: '11:30:00',
        requestedLocation: 'Emergency Ward',
        issuedInStore: 'Pharmacy Store',
        mrnStatus: 'Pending',
        items: [
        { id: generateId(), slNo: 1, itemCode: 'MED006', itemName: 'IV Saline 500ml', uom: 'bottle', reqQty: 30, apprQty: 25, issuedQty: 25, recQty: 25, rejQty: 0, balQty: 5, remarks: 'Partial approval', urgReq: true },
        { id: generateId(), slNo: 2, itemCode: 'MED007', itemName: 'Diclofenac Injection 75mg', uom: 'vial', reqQty: 40, apprQty: 40, issuedQty: 40, recQty: 40, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 3, itemCode: 'MED008', itemName: 'Insulin 40IU', uom: 'vial', reqQty: 20, apprQty: 15, issuedQty: 15, recQty: 15, rejQty: 0, balQty: 5, remarks: 'Stock shortage', urgReq: true },
        { id: generateId(), slNo: 4, itemCode: 'MED009', itemName: 'Antibiotic Ointment 15g', uom: 'tube', reqQty: 25, apprQty: 25, issuedQty: 25, recQty: 25, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 5, itemCode: 'MED010', itemName: 'ORS Sachet 5g', uom: 'sachet', reqQty: 100, apprQty: 100, issuedQty: 100, recQty: 100, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        ],
    },
    {
    issueNo: 'ISS-1003',
    mrnId: '15-0000477',
    location: 'General Ward',
    store: 'Pharmacy Store',
    requesterDate: '2024-01-12',
    requestedBy: 'Dr. Robert Lee',
    approvedDate: '2024-01-14',
    approvedBy: 'Pharmacy Manager C',
    issuedDate: '2024-01-16',
    issuedBy: 'Pharmacist D',
    receivedDate: '2024-01-17',
    status: 'Approved',
    issuedStatus: 'Issued',
    date: '2024-01-17',
    time: '09:45:00',
    requestedLocation: 'General Ward',
    issuedInStore: 'Pharmacy Store',
    mrnStatus: 'Issued',
    items: [
        { id: generateId(), slNo: 1, itemCode: 'MED011', itemName: 'Metformin 500mg', uom: 'tab', reqQty: 120, apprQty: 120, issuedQty: 120, recQty: 120, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 2, itemCode: 'MED012', itemName: 'Amlodipine 5mg', uom: 'tab', reqQty: 90, apprQty: 90, issuedQty: 90, recQty: 90, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 3, itemCode: 'MED013', itemName: 'Omeprazole 20mg', uom: 'cap', reqQty: 60, apprQty: 60, issuedQty: 60, recQty: 60, rejQty: 0, balQty: 0, remarks: '', urgReq: true },
        { id: generateId(), slNo: 4, itemCode: 'MED014', itemName: 'Ranitidine 150mg', uom: 'tab', reqQty: 80, apprQty: 80, issuedQty: 80, recQty: 80, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
        { id: generateId(), slNo: 5, itemCode: 'MED015', itemName: 'Multivitamin Syrup 100ml', uom: 'ml', reqQty: 25, apprQty: 25, issuedQty: 25, recQty: 25, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
    ],
    },
    {
  issueNo: 'ISS-1004',
  mrnId: '15-0000478',
  location: 'Pediatrics',
  store: 'Pharmacy Store',
  requesterDate: '2024-01-13',
  requestedBy: 'Dr. Emily Davis',
  approvedDate: '2024-01-15',
  approvedBy: 'Pharmacy Manager D',
  issuedDate: '2024-01-17',
  issuedBy: 'Pharmacist E',
  receivedDate: '2024-01-18',
  status: 'Rejected',
  issuedStatus: 'Not Issued',
  date: '2024-01-18',
  time: '14:20:00',
  requestedLocation: 'Pediatrics',
  issuedInStore: 'Pharmacy Store',
  mrnStatus: 'Rejected',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED016', itemName: 'Paracetamol Syrup 120mg/5ml', uom: 'ml', reqQty: 50, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 50, balQty: 50, remarks: 'Not approved', urgReq: false },
    { id: generateId(), slNo: 2, itemCode: 'MED017', itemName: 'ORS Sachet 5g', uom: 'sachet', reqQty: 100, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 100, balQty: 100, remarks: 'Not approved', urgReq: false },
    { id: generateId(), slNo: 3, itemCode: 'MED018', itemName: 'Zinc Tablet 20mg', uom: 'tab', reqQty: 80, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 80, balQty: 80, remarks: 'Not approved', urgReq: false },
    { id: generateId(), slNo: 4, itemCode: 'MED019', itemName: 'Albendazole Suspension 10ml', uom: 'ml', reqQty: 30, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 30, balQty: 30, remarks: 'Not approved', urgReq: false },
    { id: generateId(), slNo: 5, itemCode: 'MED020', itemName: 'Iron Syrup 100ml', uom: 'ml', reqQty: 40, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 40, balQty: 40, remarks: 'Not approved', urgReq: false },
  ],
},
{
  issueNo: 'ISS-1005',
  mrnId: '15-0000479',
  location: 'Surgery Ward',
  store: 'Central Store',
  requesterDate: '2024-01-14',
  requestedBy: 'Dr. Michael Green',
  approvedDate: '2024-01-16',
  approvedBy: 'Pharmacy Manager E',
  issuedDate: '2024-01-18',
  issuedBy: 'Pharmacist F',
  receivedDate: '2024-01-19',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-01-19',
  time: '15:50:00',
  requestedLocation: 'Surgery Ward',
  issuedInStore: 'Central Store',
  mrnStatus: 'Partial',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED021', itemName: 'Ceftriaxone Injection 1g', uom: 'vial', reqQty: 40, apprQty: 40, issuedQty: 20, recQty: 20, rejQty: 0, balQty: 20, remarks: 'Pending delivery', urgReq: true },
    { id: generateId(), slNo: 2, itemCode: 'MED022', itemName: 'Metronidazole IV 500mg', uom: 'vial', reqQty: 30, apprQty: 30, issuedQty: 15, recQty: 15, rejQty: 0, balQty: 15, remarks: 'Partial stock', urgReq: true },
    { id: generateId(), slNo: 3, itemCode: 'MED023', itemName: 'IV Dextrose 5% 500ml', uom: 'bottle', reqQty: 25, apprQty: 25, issuedQty: 25, recQty: 25, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
    { id: generateId(), slNo: 4, itemCode: 'MED024', itemName: 'Surgical Spirit 500ml', uom: 'bottle', reqQty: 15, apprQty: 15, issuedQty: 10, recQty: 10, rejQty: 0, balQty: 5, remarks: 'Partial issue', urgReq: false },
    { id: generateId(), slNo: 5, itemCode: 'MED025', itemName: 'Lignocaine Injection 2%', uom: 'vial', reqQty: 50, apprQty: 50, issuedQty: 50, recQty: 50, rejQty: 0, balQty: 0, remarks: '', urgReq: false },
  ],
},
{
  issueNo: 'ISS-1011',
  mrnId: '15-0000480',
  location: 'Floor 3',
  store: 'Central Store',
  requesterDate: '2024-01-20',
  requestedBy: 'Dr. Priya Sharma',
  approvedDate: '2024-01-21',
  approvedBy: 'Pharmacy Manager A',
  issuedDate: '2024-01-22',
  issuedBy: 'Pharmacist G',
  receivedDate: '2024-01-23',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-01-20',
  time: '15:00:00',
  requestedLocation: 'Floor 3',
  issuedInStore: 'Central Store',
  mrnStatus: 'Partially Received',
  items: [
    { 
      id: generateId(), slNo: 1, itemCode: 'MED030', itemName: 'Amoxicillin 500mg', 
      uom: 'tab', reqQty: 100, apprQty: 100, issuedQty: 100, recQty: 80, rejQty: 20, balQty: 0, 
      remarks: '', urgReq: true, colorIndication: 'Item Not Received'
    },
  ],
},
{
  issueNo: 'ISS-1012',
  mrnId: '15-0000481',
  location: 'Main Warehouse',
  store: 'Central Store',
  requesterDate: '2024-01-21',
  requestedBy: 'Dr. Anita Rao',
  approvedDate: '2024-01-22',
  approvedBy: 'Pharmacy Manager B',
  issuedDate: '2024-01-23',
  issuedBy: 'Pharmacist H',
  receivedDate: '2024-01-24',
  status: 'Approved',
  issuedStatus: 'Approved',
  date: '2024-01-21',
  time: '16:00:00',
  requestedLocation: 'Main Warehouse',
  issuedInStore: 'Central Store',
  mrnStatus: 'Approved',
  items: [
    { 
      id: generateId(), slNo: 1, itemCode: 'MED031', itemName: 'Insulin Injection 10ml', 
      uom: 'vial', reqQty: 5, apprQty: 5, issuedQty: 5, recQty: 0, rejQty: 0, balQty: 5, 
      remarks: '', urgReq: false, colorIndication: 'Item Not Received'
    },
  ],
},
{
  issueNo: 'ISS-1013',
  mrnId: '15-0000482',
  location: 'Warehouse B',
  store: 'Secondary Store',
  requesterDate: '2024-01-22',
  requestedBy: 'Dr. Manish Gupta',
  approvedDate: '2024-01-23',
  approvedBy: 'Pharmacy Manager C',
  issuedDate: '2024-01-24',
  issuedBy: 'Pharmacist I',
  receivedDate: '2024-01-25',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-01-22',
  time: '17:00:00',
  requestedLocation: 'Warehouse B',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Received',
  items: [
    { 
      id: generateId(), slNo: 1, itemCode: 'MED032', itemName: 'Salbutamol Inhaler 100mcg', 
      uom: 'inhaler', reqQty: 10, apprQty: 10, issuedQty: 10, recQty: 10, rejQty: 0, balQty: 0, 
      remarks: '', urgReq: true, colorIndication: 'Item Added From Issue Screen'
    },
  ],
},
{
  issueNo: 'ISS-1014',
  mrnId: '15-0000483',
  location: 'Floor 3',
  store: 'Central Store',
  requesterDate: '2024-01-23',
  requestedBy: 'Dr. Kavita Menon',
  approvedDate: '2024-01-24',
  approvedBy: 'Pharmacy Manager D',
  issuedDate: '2024-01-25',
  issuedBy: 'Pharmacist J',
  receivedDate: '2024-01-26',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-01-23',
  time: '18:00:00',
  requestedLocation: 'Floor 3',
  issuedInStore: 'Central Store',
  mrnStatus: 'Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED033', itemName: 'Paracetamol 500mg', uom: 'tab', reqQty: 25, apprQty: 25, issuedQty: 25, recQty: 25, rejQty: 0, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1015',
  mrnId: '15-0000484',
  location: 'Main Warehouse',
  store: 'Central Store',
  requesterDate: '2024-01-24',
  requestedBy: 'Dr. Nitin Joshi',
  approvedDate: '2024-01-25',
  approvedBy: 'Pharmacy Manager E',
  issuedDate: '2024-01-26',
  issuedBy: 'Pharmacist K',
  receivedDate: '2024-01-27',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-01-24',
  time: '09:00:00',
  requestedLocation: 'Main Warehouse',
  issuedInStore: 'Central Store',
  mrnStatus: 'Partially Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED034', itemName: 'IV Cannula 22G', uom: 'pcs', reqQty: 8, apprQty: 8, issuedQty: 8, recQty: 5, rejQty: 3, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1016',
  mrnId: '15-0000485',
  location: 'Warehouse B',
  store: 'Secondary Store',
  requesterDate: '2024-01-25',
  requestedBy: 'Dr. Ramesh Iyer',
  approvedDate: '2024-01-26',
  approvedBy: 'Pharmacy Manager F',
  issuedDate: '2024-01-27',
  issuedBy: 'Pharmacist L',
  receivedDate: '2024-01-28',
  status: 'Approved',
  issuedStatus: 'Approved',
  date: '2024-01-25',
  time: '10:00:00',
  requestedLocation: 'Warehouse B',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Approved',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED035', itemName: 'Ceftriaxone Injection 1g', uom: 'vial', reqQty: 3, apprQty: 3, issuedQty: 3, recQty: 0, rejQty: 0, balQty: 3, remarks: '', urgReq: true, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1017',
  mrnId: '15-0000486',
  location: 'Floor 3',
  store: 'Central Store',
  requesterDate: '2024-01-26',
  requestedBy: 'Dr. Sneha Reddy',
  approvedDate: '2024-01-27',
  approvedBy: 'Pharmacy Manager G',
  issuedDate: '2024-01-28',
  issuedBy: 'Pharmacist M',
  receivedDate: '2024-01-29',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-01-26',
  time: '11:00:00',
  requestedLocation: 'Floor 3',
  issuedInStore: 'Central Store',
  mrnStatus: 'Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED036', itemName: 'Metformin 500mg', uom: 'tab', reqQty: 4, apprQty: 4, issuedQty: 4, recQty: 4, rejQty: 0, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1018',
  mrnId: '15-0000487',
  location: 'Main Warehouse',
  store: 'Central Store',
  requesterDate: '2024-01-27',
  requestedBy: 'Dr. Arjun Mehta',
  approvedDate: '2024-01-28',
  approvedBy: 'Pharmacy Manager H',
  issuedDate: '2024-01-29',
  issuedBy: 'Pharmacist N',
  receivedDate: '2024-01-30',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-01-27',
  time: '12:00:00',
  requestedLocation: 'Main Warehouse',
  issuedInStore: 'Central Store',
  mrnStatus: 'Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED037', itemName: 'Diclofenac Gel 30g', uom: 'tube', reqQty: 2, apprQty: 2, issuedQty: 2, recQty: 2, rejQty: 0, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1019',
  mrnId: '15-0000488',
  location: 'Warehouse B',
  store: 'Secondary Store',
  requesterDate: '2024-01-28',
  requestedBy: 'Dr. Ayesha Khan',
  approvedDate: '2024-01-29',
  approvedBy: 'Pharmacy Manager I',
  issuedDate: '2024-01-30',
  issuedBy: 'Pharmacist O',
  receivedDate: '2024-01-31',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-01-28',
  time: '13:00:00',
  requestedLocation: 'Warehouse B',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Partially Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED038', itemName: 'Omeprazole 20mg', uom: 'cap', reqQty: 7, apprQty: 7, issuedQty: 7, recQty: 4, rejQty: 3, balQty: 0, remarks: '', urgReq: true, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1019',
  mrnId: '15-0000488',
  location: 'Warehouse B',
  store: 'Secondary Store',
  requesterDate: '2024-01-28',
  requestedBy: 'Dr. Ayesha Khan',
  approvedDate: '2024-01-29',
  approvedBy: 'Pharmacy Manager I',
  issuedDate: '2024-01-30',
  issuedBy: 'Pharmacist O',
  receivedDate: '2024-01-31',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-01-28',
  time: '13:00:00',
  requestedLocation: 'Warehouse B',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Partially Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED038', itemName: 'Omeprazole 20mg', uom: 'cap', reqQty: 7, apprQty: 7, issuedQty: 7, recQty: 4, rejQty: 3, balQty: 0, remarks: '', urgReq: true, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1020',
  mrnId: '15-0000489',
  location: 'Floor 3',
  store: 'Central Store',
  requesterDate: '2024-01-29',
  requestedBy: 'Dr. Ritu Sinha',
  approvedDate: '2024-01-30',
  approvedBy: 'Pharmacy Manager J',
  issuedDate: '2024-01-31',
  issuedBy: 'Pharmacist P',
  receivedDate: '2024-02-01',
  status: 'Approved',
  issuedStatus: 'Approved',
  date: '2024-01-29',
  time: '14:00:00',
  requestedLocation: 'Floor 3',
  issuedInStore: 'Central Store',
  mrnStatus: 'Approved',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED039', itemName: 'Atorvastatin 10mg', uom: 'tab', reqQty: 10, apprQty: 10, issuedQty: 10, recQty: 0, rejQty: 0, balQty: 10, remarks: '', urgReq: false, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1021',
  mrnId: '15-0000490',
  location: 'Main Warehouse',
  store: 'Central Store',
  requesterDate: '2024-01-30',
  requestedBy: 'Dr. Sanjay Verma',
  approvedDate: '2024-01-31',
  approvedBy: 'Pharmacy Manager K',
  issuedDate: '2024-02-01',
  issuedBy: 'Pharmacist Q',
  receivedDate: '2024-02-02',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-01-30',
  time: '15:00:00',
  requestedLocation: 'Main Warehouse',
  issuedInStore: 'Central Store',
  mrnStatus: 'Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED040', itemName: 'Vitamin C 500mg', uom: 'tab', reqQty: 12, apprQty: 12, issuedQty: 12, recQty: 12, rejQty: 0, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1022',
  mrnId: '15-0000491',
  location: 'Warehouse B',
  store: 'Secondary Store',
  requesterDate: '2024-01-31',
  requestedBy: 'Dr. Neha Kapoor',
  approvedDate: '2024-02-01',
  approvedBy: 'Pharmacy Manager L',
  issuedDate: '2024-02-02',
  issuedBy: 'Pharmacist R',
  receivedDate: '2024-02-03',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-01-31',
  time: '16:00:00',
  requestedLocation: 'Warehouse B',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED041', itemName: 'Hydrocortisone Cream 1%', uom: 'tube', reqQty: 5, apprQty: 5, issuedQty: 5, recQty: 5, rejQty: 0, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1023',
  mrnId: '15-0000492',
  location: 'Floor 3',
  store: 'Central Store',
  requesterDate: '2024-02-01',
  requestedBy: 'Dr. Vivek Rao',
  approvedDate: '2024-02-02',
  approvedBy: 'Pharmacy Manager M',
  issuedDate: '2024-02-03',
  issuedBy: 'Pharmacist S',
  receivedDate: '2024-02-04',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-02-01',
  time: '17:00:00',
  requestedLocation: 'Floor 3',
  issuedInStore: 'Central Store',
  mrnStatus: 'Partially Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED042', itemName: 'Furosemide 40mg', uom: 'tab', reqQty: 3, apprQty: 3, issuedQty: 3, recQty: 2, rejQty: 1, balQty: 0, remarks: '', urgReq: true, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1024',
  mrnId: '15-0000493',
  location: 'Main Warehouse',
  store: 'Central Store',
  requesterDate: '2024-02-02',
  requestedBy: 'Dr. Anjali Menon',
  approvedDate: '2024-02-03',
  approvedBy: 'Pharmacy Manager R',
  issuedDate: '2024-02-04',
  issuedBy: 'Pharmacist T',
  receivedDate: '2024-02-05',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-02-02',
  time: '18:00:00',
  requestedLocation: 'Main Warehouse',
  issuedInStore: 'Central Store',
  mrnStatus: 'Received',
  items: [
    { 
      id: generateId(), slNo: 1, itemCode: 'MED043', itemName: 'Ceftriaxone Injection 1g', uom: 'vial', 
      reqQty: 10, apprQty: 10, issuedQty: 10, recQty: 10, rejQty: 0, balQty: 0, 
      remarks: 'For surgical cases', urgReq: false, colorIndication: 'Item Added From Issue Screen' 
    },
  ],
},
{
  issueNo: 'ISS-1025',
  mrnId: '15-0000494',
  location: 'Warehouse B',
  store: 'Secondary Store',
  requesterDate: '2024-02-03',
  requestedBy: 'Dr. Ramesh Pillai',
  approvedDate: '2024-02-04',
  approvedBy: 'Pharmacy Manager N',
  issuedDate: '2024-02-05',
  issuedBy: 'Pharmacist U',
  receivedDate: '2024-02-06',
  status: 'Approved',
  issuedStatus: 'Received',
  date: '2024-02-03',
  time: '09:00:00',
  requestedLocation: 'Warehouse B',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED044', itemName: 'Metformin 500mg', uom: 'tab', reqQty: 50, apprQty: 50, issuedQty: 50, recQty: 50, rejQty: 0, balQty: 0, remarks: '', urgReq: false, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1026',
  mrnId: '15-0000495',
  location: 'Floor 2',
  store: 'Central Store',
  requesterDate: '2024-02-04',
  requestedBy: 'Dr. Kavya Narayan',
  approvedDate: '2024-02-05',
  approvedBy: 'Pharmacy Manager O',
  issuedDate: '2024-02-06',
  issuedBy: 'Pharmacist V',
  receivedDate: '2024-02-07',
  status: 'Pending',
  issuedStatus: 'Not Issued',
  date: '2024-02-04',
  time: '10:30:00',
  requestedLocation: 'Floor 2',
  issuedInStore: 'Central Store',
  mrnStatus: 'Pending',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED045', itemName: 'Atorvastatin 20mg', uom: 'tab', reqQty: 30, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 30, balQty: 30, remarks: 'Approval pending', urgReq: true, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1027',
  mrnId: '15-0000496',
  location: 'Main Warehouse',
  store: 'Central Store',
  requesterDate: '2024-02-05',
  requestedBy: 'Dr. Sanjay Mehta',
  approvedDate: '2024-02-06',
  approvedBy: 'Pharmacy Manager P',
  issuedDate: '2024-02-07',
  issuedBy: 'Pharmacist W',
  receivedDate: '2024-02-08',
  status: 'Approved',
  issuedStatus: 'Partially Received',
  date: '2024-02-05',
  time: '11:15:00',
  requestedLocation: 'Main Warehouse',
  issuedInStore: 'Central Store',
  mrnStatus: 'Partially Received',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED046', itemName: 'Amoxicillin 500mg', uom: 'cap', reqQty: 100, apprQty: 100, issuedQty: 100, recQty: 90, rejQty: 10, balQty: 0, remarks: 'Short supply received', urgReq: false, colorIndication: 'Item Not Received' },
  ],
},
{
  issueNo: 'ISS-1028',
  mrnId: '15-0000497',
  location: 'Floor 4',
  store: 'Emergency Store',
  requesterDate: '2024-02-06',
  requestedBy: 'Dr. Priya Sharma',
  approvedDate: '2024-02-07',
  approvedBy: 'Pharmacy Manager Q',
  issuedDate: '2024-02-08',
  issuedBy: 'Pharmacist X',
  receivedDate: '2024-02-09',
  status: 'Approved',
  issuedStatus: 'Issued',
  date: '2024-02-06',
  time: '12:20:00',
  requestedLocation: 'Floor 4',
  issuedInStore: 'Emergency Store',
  mrnStatus: 'Issued',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED047', itemName: 'Epinephrine Injection 1mg/mL', uom: 'amp', reqQty: 15, apprQty: 15, issuedQty: 15, recQty: 15, rejQty: 0, balQty: 0, remarks: 'Emergency stock', urgReq: true, colorIndication: 'Item Added From Issue Screen' },
  ],
},
{
  issueNo: 'ISS-1029',
  mrnId: '15-0000498',
  location: 'Warehouse C',
  store: 'Secondary Store',
  requesterDate: '2024-02-07',
  requestedBy: 'Dr. Nisha Varma',
  approvedDate: '2024-02-08',
  approvedBy: 'Pharmacy Manager R',
  issuedDate: '2024-02-09',
  issuedBy: 'Pharmacist Y',
  receivedDate: '2024-02-10',
  status: 'Rejected',
  issuedStatus: 'Not Issued',
  date: '2024-02-07',
  time: '14:00:00',
  requestedLocation: 'Warehouse C',
  issuedInStore: 'Secondary Store',
  mrnStatus: 'Rejected',
  items: [
    { id: generateId(), slNo: 1, itemCode: 'MED048', itemName: 'Warfarin 5mg', uom: 'tab', reqQty: 25, apprQty: 0, issuedQty: 0, recQty: 0, rejQty: 25, balQty: 25, remarks: 'Request not approved', urgReq: false, colorIndication: 'Item Not Received' },
  ],
},
];

/**
 * Handles GET requests for a specific MRN detail page.
 * @param {object} request - The incoming request object.
 * @param {object} context - An object containing route parameters.
 * @returns {object} A NextResponse object with the requested MRN data or an error.
 */
export async function GET(request, { params }) {
  // Extract query params
  const { searchParams } = new URL(request.url);
  const from = searchParams.get("from");
  const length = searchParams.get("length");

  // Extract route param (if you set [mrnId] in your route folder)
  const { mrnId } = params || {};

  if (mrnId) {
    const mrnDetail = mrnDetails.find(mrn => mrn.mrnId === mrnId);
    return NextResponse.json(mrnDetail || { error: "Not found" }, { status: mrnDetail ? 200 : 404 });
  }

  if (from !== null && length !== null) {
    return NextResponse.json(
      mrnDetails.slice(parseInt(from), parseInt(from) + parseInt(length))
    );
  }

  return NextResponse.json(mrnDetails);
}